---
title: "BST260_Project"
author: "Kristyn Beam and Alex Rashedi and Luis Castelo Branco"
date: "11/24/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(dplyr)
library(lubridate)
library(ggplot2)
library(readr)
```

```{r}
# Read in data on weekly influenza counts by Australian region 
aus_dat <- read.csv("https://raw.githubusercontent.com/kristynbeam/BST260Project_KB_LC_AR/main/project_data_files/aus_flu_08_17.csv")

# Identify earliest date available: 2017-09-15
min(aus_dat$week)

# Identify latest date available: 2018-01-05
max(aus_dat$week)

aus_dat <- aus_dat %>% 
  # Rename variables
  rename(week = Week.Ending..Friday., age_group = Age..group, indig = Indigenous.status, flu_type = Type.Subtype, state = State, sex = Sex) %>% 
  # Select variables
  select(week, state, age_group, sex, indig, flu_type)

# Convert variable types
aus_dat$week <- mdy(aus_dat$week)
# aus_dat$flu_type <- as.character(aus_dat$flu_type)
# aus_dat$state <- as.character(aus_dat$state)
# aus_dat$sex <- as.character(aus_dat$sex)

# View aus_dat
head(aus_dat)
```

```{r}
# Create count data frame using aus_dat
aus_dat_case <- aus_dat %>% 
  group_by(week, state, age_group, flu_type, sex) %>% 
  summarize(n_cases = n())
```

```{r}
# Read in Australian disease data
aus_data <- read.csv("https://raw.githubusercontent.com/kristynbeam/BST260Project_KB_LC_AR/main/project_data_files/Australian_data_clean.csv")

# removing all NA values
not_all_na <- function(x) any(!is.na(x))

aus_data <- aus_data %>%
  select_if(not_all_na) %>%
  # Rename variable
  rename("Disease"="X")

head(aus_data)

# Create case data frame and reshape to long format
aus_data_cases <- aus_data %>% 
  select("Disease":"Aust_n") %>% 
  rename("ACT"="ACT_n", "NSW"="NSW_n", "NT"="NT_n", "Qld"="Qld_n", "SA"="SA_n", "Tas"= "Tas_n", "Vic"= "Vic_n", "WA"= "WA_n", "Australia"= "Aust_n") %>% 
  arrange("Date") %>% 
  gather(State, Cases, c("ACT":"Australia"))

# Create rate data frame and reshape to long format
aus_data_rates <- aus_data %>% 
  select("Disease"|"Date"|"ACT_rate":"Aust_rate") %>% 
  rename("ACT"="ACT_rate", "NSW"="NSW_rate", "NT"="NT_rate", "Qld"="Qld_rate", "SA"="SA_rate", "Tas"= "Tas_rate", "Vic"="Vic_rate", "WA"="WA_rate", "Australia"="Aust_rate") %>% 
  arrange("Date") %>% 
  gather(State, Rates, c("ACT":"Australia")) 

# Join cases and rates data frames
aus_total <- left_join(aus_data_cases, aus_data_rates)

# Convert variable types
aus_total$Date <- mdy(aus_total$Date)
aus_total$Cases <- as.numeric(aus_total$Cases)
aus_total$Rates <- as.numeric(aus_total$Rates)

# View aus_total
head(aus_total)

# Rename provinces
aus_total$State <- recode(aus_total$State, "Australian Capital Territory" = "ACT", "New South Wales" = "NSW", "Northern Territory" = "NT", "Queensland" = "Qld", "South Australia" = "SA", "Tasmania" = "Tas", "Victoria" = "Vic", "Western Australia" = "WA")


#Filter aus_total df to only include diseases that have a rate of disease of > 0.2/100,000 
aus_total_high <- aus_total %>% 
  filter(Rates >= 0.2, Disease != "COVID-19")

#How many diseases are we left with in this case? n = 42
aus_total_high %>% 
  group_by(Disease) %>% 
  summarize()

aus_total_high %>% 
  ggplot(aes(Date, Rates, color = Disease)) +
  geom_line()

# Save aus_total and aus_total_high so they can be brought into Shiny app
write.csv(aus_total, file = "~/Desktop/Project_repo/BST260Project_KB_LC_AR/project_data_files/aus.total.csv")
#write.csv(aus_total, file="https://raw.githubusercontent.com/kristynbeam/BST260Project_KB_LC_AR/main/project_data_files/aus_total.csv")
#write.csv(aus_total_high, file="https://raw.githubusercontent.com/kristynbeam/BST260Project_KB_LC_AR/main/project_data_files/aus_total_high.csv")
```

```{r}
# Create COVID-19 data frame
aus_total_covid <- aus_total %>% 
  filter(Disease == "COVID-19")

# Create test COVID-19 plots
p1 <- ggplot(data = aus_total_covid, 
            aes(x = Date, 
                y = Cases))
p1 + geom_line(aes(color = State)) +
  ggtitle("Covid Cases by Region") +
  ylim(0, 70000)

p1

p2 <- ggplot(data = aus_total_covid, 
             aes(x = Date, 
                 y = Rates))
p2 + geom_line(aes(color = State)) +
  ggtitle("Covid Rates by Region") +
  ylim(0, 450)

# Create influenza data frame (monthly counts and rates by Australian region)
aus_total_influenza <- aus_total %>% 
  filter(Disease == "Influenza (laboratory confirmed)")

# Identify earliest date available: 2018-11-30
min(aus_total_influenza$Date)

# Identify latest date available: 2020-10-31
max(aus_total_influenza$Date)

# Create test influenza plots
p3 <- ggplot(data = aus_total_influenza, 
             aes(x = Date, 
                 y = Cases))
p3 + geom_line(aes(color = State)) +
  ggtitle("Influenza Cases by Region") +
  ylim(0, 70500)

p4 <- ggplot(data = aus_total_influenza, 
             aes(x = Date, 
                 y = Rates))
p4 + geom_line(aes(color = State)) +
  ggtitle("Influenza Rate by Region") +
  ylim(0, 450)
```


```{r}
# #Read in policy data
# pol_dat <- read.csv("~/Desktop/Project_repo/BST260Project_KB_LC_AR/project_data_files/coronanet_release.csv")
# head(pol_dat)
# 
# #Filtered policy data to just Australia
# pol_dat_aus <- pol_dat %>% 
#   filter(ISO_A2 == "AU" & ISO_A3 == "AUS") %>% 
#   arrange(date_start)
# 
# #Read in uid lookup dataset
# countries <- read.csv("~/Desktop/Project_repo/BST260Project_KB_LC_AR/project_data_files/UID_ISO_FIPS_LookUp_Table.csv")
# head(countries)
# countries <- countries %>% 
#   rename(ISO_A2 = iso2, ISO_A3 = iso3)
# 
# countries %>% 
#   filter(ISO_A3 == "AUS")
# 
# #Filtered australia policy data to include columns of significance
# pol_dat_aus <- pol_dat_aus %>% 
#   select(description, date_announced, date_start, date_end, country, ISO_A2, ISO_A3, domestic_policy, province, type, type_sub_cat, type_text, target_country, target_province, target_who_what, index_high_est, index_med_est, index_low_est, index_country_rank, compliance, enforcer) %>% 
#   group_by(date_announced) %>% 
#   arrange(province)
# 
# #A higher policy activity score indicates more restrictions at an earlier date. 

```

```{r}
# Read in Australian policy data by pulling most up-to-date version from Github
pol_dat_aus = read_csv("https://raw.githubusercontent.com/saudiwin/corona_tscs/master/data/CoronaNet/data_country/coronanet_release/coronanet_release_Australia.csv")

pol_dat_aus <- pol_dat_aus %>%
  # Group pol_dat_aus by province and policy type
  group_by(province, 
           type) %>%
  # Arrange by date policy goes into effect
  arrange(date_start) %>%
  # Keep only first observation within each province-policy type group
  slice() %>%
  # Ungroup
  ungroup() %>%
  # Filter to keep only policies that target Australia
  filter(target_country == "Australia")

# pol_dat_aus$type <- as.factor(pol_dat_aus$type)
# pol_dat_aus$type_sub_cat <- as.factor(pol_dat_aus$type_sub_cat)
# pol_dat_aus$target_who_what <- as.factor(pol_dat_aus$target_who_what)

# View pol_dat_aus
head(pol_dat_aus)

# Save pol_dat_aus so it can be brought into Shiny app
write.csv(pol_dat_aus, file="https://raw.githubusercontent.com/kristynbeam/BST260Project_KB_LC_AR/main/project_data_files/pol_dat_aus.csv")
```

```{r}
   country_names <- recode(pol_dat_aus$province, "Australian Capital Territory" = "ACT", "New South Wales" = "NSW", "Northern Territory" = "NT", "Queensland" = "Qld", "South Australia" = "SA",  "Tasmania" = "Tas", "Victoria" = "Vic", "Western Australia" = "WA")

pol_dat_aus$province <- country_names

#create smaller DF for each province
pol_ACT <- pol_dat_aus %>% 
  filter(province == "ACT") %>% 
  group_by(type) %>% 
  select(province, type, date_announced, date_start)

pol_NSW <- pol_dat_aus %>% 
  filter(province == "NSW") %>% 
  group_by(type) %>% 
  select(province, type, date_announced, date_start)

pol_NT <- pol_dat_aus %>% 
  filter(province == "NT") %>% 
  group_by(type) %>% 
  select(province, type, date_announced, date_start)

pol_Qld <- pol_dat_aus %>% 
  filter(province == "Qld") %>% 
  group_by(type) %>% 
  select(province, type, date_announced, date_start)

pol_SA <- pol_dat_aus %>% 
  filter(province == "SA") %>% 
  group_by(type) %>% 
  select(province, type, date_announced, date_start)

pol_Tas <- pol_dat_aus %>% 
  filter(province == "Tas") %>% 
  group_by(type) %>% 
  select(province, type, date_announced, date_start)

pol_Vic <- pol_dat_aus %>% 
  filter(province == "Vic") %>% 
  group_by(type) %>% 
  select(province, type, date_announced, date_start)

pol_WA <- pol_dat_aus %>% 
  filter(province == "WA") %>% 
  group_by(type) %>% 
  select(province, type, date_announced, date_start)
```



```{r}
# https://www-nature-com.ezp-prod1.hul.harvard.edu/articles/s41562-020-01009-0
# "The most effective NPIs include curfews, lockdowns and closing and restricting places where people gather in smaller or large numbers for an extended period of time. This includes small gathering cancellations (closures of shops, restaurants, gatherings of 50 persons or fewer, mandatory home working and so on) and closure of educational institutions."

# Test graph
aus_total %>%
  filter(State == "NSW" & Date >= "2020-01-01" & Disease %in% c("Influenza (laboratory confirmed)", "COVID-19")) %>%
  ggplot(aes(x = Date, 
             y = Rates)) +
  geom_line(aes(color = Disease), 
            alpha = 0.5) +
  # 2020-03-16 is date of first policy restriction in NSW (restriction of mass gatherings)
  geom_vline(alpha = 0.5, 
             xintercept = as.numeric(as.Date("2020-03-16")), 
             color = "blue") +
  labs(x = "Date",
       y = "Rate") +
  ggtitle("Covid rates in NSW over time") +
  scale_x_date(date_breaks = "1 month", 
               date_labels = "%b")
```


```{r}
# Read in Johns Hopkins UID lookup table
uid_lookup_table = read_csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/UID_ISO_FIPS_LookUp_Table.csv")

# Filter uid_lookup_table to only include relevant observations
uid_lookup_table <- uid_lookup_table %>% 
   filter(`Country_Region` == "Australia" & !is.na(`Province_State`))

# View uid_lookup_table
head(uid_lookup_table)

# # Merge pol_dat_aus with uid_lookup_table (run this code for producing maps dataset)
# pol_dat_aus <- pol_dat_aus %>%
#    left_join(uid_lookup_table, by = c("province" = "Province_State"))
```

```{r}
#Creating a variable: drop in influenza cases from year 1 (Nov/18 to Oct/19) compared to year 2 (Nov19 to Oct/20)
aus_total_influenza$Date <- ymd(aus_total_influenza$Date)

head(aus_total_influenza)

aus_total_influenza_year1<- aus_total_influenza %>% filter (Date <="2019-10-31") %>%group_by(State)%>%summarize(year1=sum(Cases))
aus_total_influenza_year2<- aus_total_influenza %>% filter (Date > "2019-10-31") %>%group_by(State)%>%summarize(year2=sum(Cases))
aus_total_influenza_diff<- left_join(aus_total_influenza_year1, aus_total_influenza_year2)%>%mutate(drop=(year1-year2)/year1)

```


```{r}
#web scraping for a dataset that containd the Population and Population density for the provinces
library(rvest)
url <- "https://www.worldatlas.com/articles/which-australian-states-territories-have-the-highest-density-of-population.html"
h <- read_html(url)
density<- h %>% html_nodes("table") %>% .[1]
density <- density %>% html_table %>% .[[1]] 

density<- density%>%rename("State"= "State / Territory")%>%rename("density"="Density (persons per km2)") %>% mutate(State=recode(State,"Australian Capital Territory"="ACT", "New South Wales"="NSW", "Northern Territory"="NT", "Queensland"="Qld", "South Australia"="SA", "Tasmania"="Tas", "Victoria"="Vic", "Western Australia"="WA"))

density$Population<-as.numeric(gsub(",","",density$Population))

#joining the datasets
aus_total_influenza_diff<-left_join(aus_total_influenza_diff, density)

head(aus_total_influenza_diff)

#linear regressions to see if population or population density were associated with the drop in cases

linearMod <- lm(drop ~ density , data=aus_total_influenza_diff) 
confint.lm(linearMod)
summary(linearMod)

linearMod2 <- lm(drop ~ Population , data=aus_total_influenza_diff) 
confint.lm(linearMod2)
summary(linearMod2)

```

